
TOP = ..

TARGET = gof23pattern.a

INCLUDE_DIR += -Iinlcude

SRC_C = $(wildcard *.cpp)
SRC_C += $(wildcard singleton/*.cpp)
SRC_C += $(wildcard builder/*.cpp)
SRC_C += $(wildcard prototype/*.cpp)
SRC_C += $(wildcard bridge/*.cpp)
SRC_C += $(wildcard decorator/*.cpp)
SRC_C += $(wildcard composite/*.cpp)




include $(TOP)/compile/common.mf

